### ISSUE TITLE
/src/lib is hardcoded, i want to put my components elsewhere

### ISSUE THREAD

**Issue by swyxio** [d4rekanguok/talenote#8]
hey thanks for this great project! i just tried it out with this in `component.svelte`:

```html
<script context="module">
	// Write a glob to get your handsome components here. Are they in `lib`? or maybe `components`?
	const modules = import.meta.globEager('/src/components/**/*.svelte');
</script>

<script>
	import { DisplayComponent } from 'talenote';
</script>

<DisplayComponent {modules} />
```

but it is showing an error: 
![image](https://user-images.githubusercontent.com/6764957/152636832-f13e7e9d-36c0-4d6d-8562-3c967f71d7ff.png)

the sourcemap shows that src/lib is hardcoded 
![image](https://user-images.githubusercontent.com/6764957/152636851-517b3cb6-acf9-4362-9c84-eb02af87b238.png)

**Comment by d4rekanguok** [comment]
Whoa, thanks so much for giving it a try swyx!! Could you check `/talenote/index.svelte`? I put a `getComponentName` function there to create nicer display names for the component list 😅

**Comment by swyxio** [comment]
realized that just now and came to close it, didnt realize it was under my control 😅
